import { Context, Effect, FileSystem, Layer, Path } from "effect";
import type { PlatformError } from "effect/PlatformError";
import { rm } from "node:fs/promises";
import {
  collectDocumentIds,
  collectStringFieldValues,
  documentLookupKey,
  documentModuleBasename,
  getterQueryTypeFields,
  literalUnionType,
  omitKeysUnionType,
  resolveCollectionGenerate,
  resolveSingletonGenerate,
  sortByListSort,
  toDocumentExport,
  toListExport,
} from "../codegen";
import type { AnyContent, AnhurConfig } from "../config";
import { isCollection, isSingleton, resolveLocalization } from "../config";
import type { CollectedDocument } from "./content-collector";

export type BuiltSource = {
  source: AnyContent;
  documents: CollectedDocument[];
};

function serializeValue(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function jsModule(body: string): string {
  return `// generated by @anhur/core — do not edit\n${body}\n`;
}

function collectionGetterSource(
  getterName: string,
  sourceName: string,
  lookupBy: readonly string[],
  loaderEntries: string[],
): string {
  const lookupFields = lookupBy.filter((f) => f !== "id");
  const requiredHint = ["id", ...lookupFields]
    .map((f) => `query.${f}`)
    .join(" or ");

  const fieldChecks = lookupFields
    .map(
      (field) =>
        `  if ((typeof keyPart !== "string" || keyPart.length === 0) && typeof query.${field} === "string" && query.${field}.length > 0) {
    keyPart = query.${field};
  }`,
    )
    .join("\n");

  return `const loaders = {
${loaderEntries.join("\n")}
};

/**
 * Load one full ${sourceName} document (includes fields omitted from the list index).
 * @param {{ locale?: string, id?: string${lookupFields.map((f) => `, ${f}?: string`).join("")} }} query
 */
export async function ${getterName}(query = {}) {
  const locale = query.locale ?? "default";
  let keyPart = query.id;
${fieldChecks}
  if (typeof keyPart !== "string" || keyPart.length === 0) {
    throw new Error("${getterName} requires ${requiredHint}");
  }
  const key = locale + ":" + keyPart;
  const loader = loaders[key];
  if (!loader) {
    throw new Error("${sourceName} document not found: " + key);
  }
  return (await loader()).default;
}
`;
}

function singletonGetterSource(
  getterName: string,
  sourceName: string,
  loaderEntries: string[],
): string {
  return `const loaders = {
${loaderEntries.join("\n")}
};

/**
 * Load one locale variant of ${sourceName}.
 * @param {{ locale?: string }} query
 */
export async function ${getterName}(query = {}) {
  const locale = query.locale ?? "default";
  const key = locale + ":${sourceName}";
  const loader = loaders[key];
  if (!loader) {
    throw new Error("${sourceName} document not found: " + key);
  }
  return (await loader()).default;
}
`;
}

/**
 * Writes `.anhur/generated` modules from collected sources.
 *
 * Collections (default `split: "light"`):
 * - light list without `listOmit` fields (default: `body`)
 * - per-document modules under `documents/{name}/`
 * - async getter for on-demand full documents
 *
 * `index.js` re-exports with `export { … } from` so unused collections can tree-shake.
 */
export class Generator extends Context.Service<
  Generator,
  {
    readonly write: (options: {
      config: AnhurConfig;
      configPath: string;
      outputDir: string;
      built: BuiltSource[];
    }) => Effect.Effect<void, PlatformError>;
  }
>()("@anhur/core/Generator") {
  static readonly layer: Layer.Layer<
    Generator,
    never,
    FileSystem.FileSystem | Path.Path
  > = Layer.effect(
    Generator,
    Effect.gen(function* () {
      const fs = yield* FileSystem.FileSystem;
      const path = yield* Path.Path;

      const writeText = (
        filePath: string,
        body: string,
      ): Effect.Effect<void, PlatformError> =>
        Effect.gen(function* () {
          yield* fs.makeDirectory(path.dirname(filePath), { recursive: true });
          yield* fs.writeFileString(filePath, body);
        });

      const removeQuiet = (target: string): Effect.Effect<void, never> =>
        Effect.promise(() => rm(target, { recursive: true, force: true })).pipe(
          Effect.catch(() => Effect.void),
        );

      const writeCollection = (
        outputDir: string,
        item: BuiltSource,
      ): Effect.Effect<void, PlatformError> =>
        Effect.gen(function* () {
          if (!isCollection(item.source)) return;

          const source = item.source;
          const gen = resolveCollectionGenerate(source);
          const docsDir = path.join(outputDir, "documents", source.name);

          const listItems = sortByListSort(
            item.documents.map((doc) =>
              toListExport(doc.data, doc._meta, gen.listOmit),
            ),
            gen.listSort,
          );

          yield* writeText(
            path.join(outputDir, `${gen.listName}.js`),
            jsModule(`export default ${serializeValue(listItems)}`),
          );

          if (!gen.emitDocuments) return;

          const loaderEntries: string[] = [];
          const seenKeys = new Set<string>();

          const addLoader = (key: string, importPath: string) => {
            if (seenKeys.has(key)) return;
            seenKeys.add(key);
            loaderEntries.push(
              `  ${JSON.stringify(key)}: () => import(${JSON.stringify(importPath)}),`,
            );
          };

          for (const doc of item.documents) {
            const basename = documentModuleBasename(
              doc._meta.locale,
              doc._meta.id,
            );
            const fileName = `${basename}.js`;
            const absDocPath = path.join(docsDir, fileName);
            const full = toDocumentExport(doc.data, doc._meta);

            yield* writeText(
              absDocPath,
              jsModule(`export default ${serializeValue(full)}`),
            );

            const importPath = `./documents/${source.name}/${fileName}`;
            addLoader(
              documentLookupKey(doc._meta.locale, doc._meta.id),
              importPath,
            );

            for (const field of gen.lookupBy) {
              if (field === "id") continue;
              const value = doc.data[field];
              if (typeof value === "string" && value.length > 0) {
                addLoader(
                  documentLookupKey(doc._meta.locale, value),
                  importPath,
                );
              }
            }
          }

          yield* writeText(
            path.join(outputDir, `${gen.getterName}.js`),
            jsModule(
              collectionGetterSource(
                gen.getterName,
                source.name,
                gen.lookupBy,
                loaderEntries,
              ),
            ),
          );
        });

      const writeSingleton = (
        config: AnhurConfig,
        outputDir: string,
        item: BuiltSource,
      ): Effect.Effect<void, PlatformError> =>
        Effect.gen(function* () {
          if (!isSingleton(item.source)) return;

          const localization = resolveLocalization(config, item.source);
          const gen = resolveSingletonGenerate(
            item.source,
            localization != null,
          );

          let exportValue: unknown = item.documents[0]
            ? toDocumentExport(item.documents[0].data, item.documents[0]._meta)
            : undefined;

          if (localization) {
            const preferred =
              item.documents.find(
                (d) => d._meta.locale === localization.defaultLocale,
              ) ?? item.documents[0];
            exportValue = preferred
              ? toDocumentExport(preferred.data, preferred._meta)
              : undefined;
          }

          yield* writeText(
            path.join(outputDir, `${gen.exportName}.js`),
            jsModule(`export default ${serializeValue(exportValue)}`),
          );

          if (gen.emitAll) {
            yield* writeText(
              path.join(outputDir, `${gen.variantsName}.js`),
              jsModule(
                `export default ${serializeValue(
                  item.documents.map((d) => toDocumentExport(d.data, d._meta)),
                )}`,
              ),
            );
          }

          if (!gen.emitDocuments) return;

          const docsDir = path.join(outputDir, "documents", item.source.name);
          const loaderEntries: string[] = [];

          for (const doc of item.documents) {
            const basename = documentModuleBasename(
              doc._meta.locale,
              doc._meta.id,
            );
            const fileName = `${basename}.js`;
            const absDocPath = path.join(docsDir, fileName);
            const full = toDocumentExport(doc.data, doc._meta);

            yield* writeText(
              absDocPath,
              jsModule(`export default ${serializeValue(full)}`),
            );

            const importPath = `./documents/${item.source.name}/${fileName}`;
            const key = documentLookupKey(doc._meta.locale, item.source.name);
            loaderEntries.push(
              `  ${JSON.stringify(key)}: () => import(${JSON.stringify(importPath)}),`,
            );
          }

          yield* writeText(
            path.join(outputDir, `${gen.getterName}.js`),
            jsModule(
              singletonGetterSource(
                gen.getterName,
                item.source.name,
                loaderEntries,
              ),
            ),
          );
        });

      const writeDataModules = (
        config: AnhurConfig,
        outputDir: string,
        built: BuiltSource[],
      ): Effect.Effect<void, PlatformError> =>
        Effect.gen(function* () {
          yield* removeQuiet(path.join(outputDir, "documents"));

          for (const item of built) {
            if (isCollection(item.source)) {
              yield* writeCollection(outputDir, item);
            } else {
              yield* writeSingleton(config, outputDir, item);
            }
          }
        });

      const writeIndexJs = (
        config: AnhurConfig,
        outputDir: string,
        built: BuiltSource[],
      ): Effect.Effect<void, PlatformError> =>
        Effect.gen(function* () {
          const lines: string[] = [
            "// generated by @anhur/core — do not edit",
            "",
          ];

          for (const item of built) {
            if (isCollection(item.source)) {
              const gen = resolveCollectionGenerate(item.source);
              lines.push(
                `export { default as ${gen.listName} } from "./${gen.listName}.js";`,
              );
              if (gen.emitDocuments) {
                lines.push(
                  `export { ${gen.getterName} } from "./${gen.getterName}.js";`,
                );
              }
              continue;
            }

            const localization = resolveLocalization(config, item.source);
            const gen = resolveSingletonGenerate(
              item.source,
              localization != null,
            );
            lines.push(
              `export { default as ${gen.exportName} } from "./${gen.exportName}.js";`,
            );
            if (gen.emitAll) {
              lines.push(
                `export { default as ${gen.variantsName} } from "./${gen.variantsName}.js";`,
              );
            }
            if (gen.emitDocuments) {
              lines.push(
                `export { ${gen.getterName} } from "./${gen.getterName}.js";`,
              );
            }
          }

          lines.push("");
          yield* writeText(path.join(outputDir, "index.js"), lines.join("\n"));
        });

      const toImportPath = (fromDir: string, targetFile: string): string => {
        let relative = path
          .relative(fromDir, targetFile)
          .split(path.sep)
          .join("/");
        if (!relative.startsWith(".")) {
          relative = `./${relative}`;
        }
        return relative.replace(/\.(mts|cts|tsx|ts|mjs|cjs|js)$/, "");
      };

      const writeIndexDts = (
        config: AnhurConfig,
        outputDir: string,
        configPath: string,
        built: BuiltSource[],
      ): Effect.Effect<void, PlatformError> =>
        Effect.gen(function* () {
          const importPath = toImportPath(outputDir, configPath);
          const lines: string[] = [
            "// generated by @anhur/core — do not edit",
            `import type { GetTypeByName } from "@anhur/core";`,
            `import type configuration from "${importPath}";`,
            "",
          ];

          for (const item of built) {
            const { source } = item;
            lines.push(
              `export type ${source.typeName} = GetTypeByName<typeof configuration, "${source.name}">;`,
            );

            if (isSingleton(source)) {
              const localization = resolveLocalization(config, source);
              const gen = resolveSingletonGenerate(
                source,
                localization != null,
              );
              const optional =
                source.optional || item.documents.length === 0
                  ? " | undefined"
                  : "";
              lines.push(
                `export declare const ${gen.exportName}: ${source.typeName}${optional};`,
              );
              if (gen.emitAll) {
                lines.push(
                  `export declare const ${gen.variantsName}: Array<${source.typeName}>;`,
                );
              }
              if (gen.emitDocuments) {
                lines.push(
                  `export declare function ${gen.getterName}(query?: { locale?: string }): Promise<${source.typeName}>;`,
                );
              }
            } else if (isCollection(source)) {
              const gen = resolveCollectionGenerate(source);
              const documentType = source.typeName;

              if (gen.listOmit.length === 0) {
                lines.push(
                  `export type ${gen.listItemTypeName} = ${documentType};`,
                );
              } else {
                lines.push(
                  `export type ${gen.listItemTypeName} = Omit<${documentType}, ${omitKeysUnionType(gen.listOmit)}>;`,
                );
              }

              if (gen.arrayTypeName !== documentType) {
                lines.push(
                  `export type ${gen.arrayTypeName} = Array<${documentType}>;`,
                );
              }

              if (gen.emitIds) {
                lines.push(
                  `export type ${documentType}Id = ${literalUnionType(collectDocumentIds(item.documents))};`,
                );
              }

              if (gen.emitSlugs) {
                lines.push(
                  `export type ${documentType}Slug = ${literalUnionType(collectStringFieldValues(item.documents, "slug"))};`,
                );
              }

              lines.push(
                `export declare const ${gen.listName}: Array<${gen.listItemTypeName}>;`,
              );

              if (gen.emitDocuments) {
                lines.push(
                  `export declare function ${gen.getterName}(query?: { ${getterQueryTypeFields(gen.lookupBy)} }): Promise<${documentType}>;`,
                );
              }
            }
            lines.push("");
          }

          lines.push("export {};");
          lines.push("");

          yield* writeText(
            path.join(outputDir, "index.d.ts"),
            lines.join("\n"),
          );
        });

      const write = (options: {
        config: AnhurConfig;
        configPath: string;
        outputDir: string;
        built: BuiltSource[];
      }): Effect.Effect<void, PlatformError> =>
        Effect.gen(function* () {
          const { config, configPath, outputDir, built } = options;
          yield* fs.makeDirectory(outputDir, { recursive: true });
          yield* writeText(path.join(outputDir, ".keep"), "");
          yield* writeDataModules(config, outputDir, built);
          yield* writeIndexJs(config, outputDir, built);
          yield* writeIndexDts(config, outputDir, configPath, built);
        });

      return Generator.of({ write });
    }),
  );
}
