/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as PagesIndexRouteImport } from './routes/pages.index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog.index'
import { Route as AuthorsIndexRouteImport } from './routes/authors.index'
import { Route as AuthorsIdRouteImport } from './routes/authors.$id'
import { Route as PostsLocaleSlugRouteImport } from './routes/posts.$locale.$slug'
import { Route as PagesLocaleSlugRouteImport } from './routes/pages.$locale.$slug'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsIdRoute = AuthorsIdRouteImport.update({
  id: '/authors/$id',
  path: '/authors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsLocaleSlugRoute = PostsLocaleSlugRouteImport.update({
  id: '/posts/$locale/$slug',
  path: '/posts/$locale/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesLocaleSlugRoute = PagesLocaleSlugRouteImport.update({
  id: '/pages/$locale/$slug',
  path: '/pages/$locale/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors/$id': typeof AuthorsIdRoute
  '/authors/': typeof AuthorsIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/pages/': typeof PagesIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/pages/$locale/$slug': typeof PagesLocaleSlugRoute
  '/posts/$locale/$slug': typeof PostsLocaleSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors/$id': typeof AuthorsIdRoute
  '/authors': typeof AuthorsIndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/pages': typeof PagesIndexRoute
  '/posts': typeof PostsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/search': typeof SearchIndexRoute
  '/pages/$locale/$slug': typeof PagesLocaleSlugRoute
  '/posts/$locale/$slug': typeof PostsLocaleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors/$id': typeof AuthorsIdRoute
  '/authors/': typeof AuthorsIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/pages/': typeof PagesIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/pages/$locale/$slug': typeof PagesLocaleSlugRoute
  '/posts/$locale/$slug': typeof PostsLocaleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/authors/$id'
    | '/authors/'
    | '/changelog/'
    | '/pages/'
    | '/posts/'
    | '/products/'
    | '/search/'
    | '/pages/$locale/$slug'
    | '/posts/$locale/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/authors/$id'
    | '/authors'
    | '/changelog'
    | '/pages'
    | '/posts'
    | '/products'
    | '/search'
    | '/pages/$locale/$slug'
    | '/posts/$locale/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/authors/$id'
    | '/authors/'
    | '/changelog/'
    | '/pages/'
    | '/posts/'
    | '/products/'
    | '/search/'
    | '/pages/$locale/$slug'
    | '/posts/$locale/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthorsIdRoute: typeof AuthorsIdRoute
  AuthorsIndexRoute: typeof AuthorsIndexRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  PagesIndexRoute: typeof PagesIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  PagesLocaleSlugRoute: typeof PagesLocaleSlugRoute
  PostsLocaleSlugRoute: typeof PostsLocaleSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/': {
      id: '/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/': {
      id: '/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$id': {
      id: '/authors/$id'
      path: '/authors/$id'
      fullPath: '/authors/$id'
      preLoaderRoute: typeof AuthorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$locale/$slug': {
      id: '/posts/$locale/$slug'
      path: '/posts/$locale/$slug'
      fullPath: '/posts/$locale/$slug'
      preLoaderRoute: typeof PostsLocaleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$locale/$slug': {
      id: '/pages/$locale/$slug'
      path: '/pages/$locale/$slug'
      fullPath: '/pages/$locale/$slug'
      preLoaderRoute: typeof PagesLocaleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthorsIdRoute: AuthorsIdRoute,
  AuthorsIndexRoute: AuthorsIndexRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  PagesIndexRoute: PagesIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  PagesLocaleSlugRoute: PagesLocaleSlugRoute,
  PostsLocaleSlugRoute: PostsLocaleSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
