import type {
  PluginGenerateContext,
  SourceSnapshot,
  TransformDocument,
} from "@anhur/core/plugin";
import { create, insert, save } from "@orama/orama";
import { STEMMER_LANGUAGES, isStemmerLanguage } from "./stemmers";
import { tokenizerFor } from "./tokenizer-for";
import type { TokenizerSpec } from "./tokenizer";
import type {
  AnhurSearchIndex,
  JsonObject,
  JsonValue,
  OramaFieldType,
  OramaFieldValue,
  OramaSchema,
  StoreObject,
  StoreValue,
} from "./types";

const FIELD_TYPES: readonly OramaFieldType[] = [
  "string",
  "number",
  "boolean",
  "enum",
  "string[]",
  "number[]",
  "boolean[]",
  "enum[]",
];
const RESERVED = new Set(["id", "collection", "documentId", "store"]);
const HEADER = "// generated by @anhur/orama — do not edit";
/** Locale key of an index built without localization. */
const DEFAULT_KEY = "default";

/** A value `index()` may give a field (`undefined` = not indexed). */
type IndexValue = OramaFieldValue<OramaFieldType> | undefined;

/** `index()` result with the field names erased. */
type RuntimeIndexValues = { readonly [field: string]: IndexValue };

/** A collection entry with its document type erased (checked at the `orama()` call). */
type RuntimeCollection = {
  readonly schema: OramaSchema;
  /** Required by the types; checked again for configs written in JavaScript. */
  readonly index?: (document: TransformDocument) => RuntimeIndexValues;
  readonly store?: (document: TransformDocument) => StoreObject;
};

/** Runtime view of `orama()` options (types were checked at the call site). */
export type RuntimeOramaOptions = {
  readonly collections: { readonly [name: string]: RuntimeCollection };
  readonly languages?: { readonly [locale: string]: string };
  readonly path?: string;
};

function isFieldType(value: unknown): value is OramaFieldType {
  return FIELD_TYPES.some((type) => type === value);
}

/** A plain `{}` object (not a `Date`, `Map`, class instance, array, …). */
function isPlainObject<TValue>(
  value: TValue,
): value is Extract<TValue, object> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return false;
  }
  const prototype: object | null = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

function message(cause: unknown): string {
  return cause instanceof Error ? cause.message : String(cause);
}

function list(values: readonly string[]): string {
  return values.map((value) => `"${value}"`).join(", ");
}

function isSearchable(type: OramaFieldType): boolean {
  return type === "string" || type === "string[]";
}

function checkCollectionSchema(name: string, schema: OramaSchema): void {
  for (const [field, type] of Object.entries(schema)) {
    if (RESERVED.has(field)) {
      throw new Error(
        `orama: collection "${name}" uses the reserved field "${field}".`,
      );
    }
    if (field.length === 0 || field.includes(".")) {
      throw new Error(
        `orama: collection "${name}" field "${field}" is not a valid name (no "." and not empty).`,
      );
    }
    if (!isFieldType(type)) {
      throw new Error(
        `orama: collection "${name}" field "${field}" has the unknown type "${String(type)}".`,
      );
    }
  }
  if (!Object.values(schema).some(isSearchable)) {
    throw new Error(
      `orama: collection "${name}" has no "string" or "string[]" field, so no search can find it.`,
    );
  }
}

function mergeSchemas(
  collections: RuntimeOramaOptions["collections"],
): OramaSchema {
  const merged = new Map<string, OramaFieldType>();
  for (const [name, config] of Object.entries(collections)) {
    checkCollectionSchema(name, config.schema);
    for (const [field, type] of Object.entries(config.schema)) {
      const existing = merged.get(field);
      if (existing !== undefined && existing !== type) {
        throw new Error(
          `orama: field "${field}" is "${existing}" in one collection and "${type}" in another.`,
        );
      }
      merged.set(field, type);
    }
  }
  return { ...Object.fromEntries(merged), collection: "enum" };
}

/**
 * `languages` checked against the build's locales (or `"default"` without
 * localization) and the supported stemmers.
 */
function stemmersByLocale(
  languages: RuntimeOramaOptions["languages"],
  keys: readonly string[],
): ReadonlyMap<string, TokenizerSpec["stemmer"]> {
  const result = new Map<string, TokenizerSpec["stemmer"]>();
  for (const [key, language] of Object.entries(languages ?? {})) {
    if (!keys.includes(key)) {
      throw new Error(
        `orama: languages has the key "${key}", which is not ${keys.length === 1 && keys[0] === DEFAULT_KEY ? `"${DEFAULT_KEY}" (the key to use without localization)` : `a locale; use one of ${list(keys)}`}.`,
      );
    }
    if (!isStemmerLanguage(language)) {
      throw new Error(
        `orama: languages.${key} is "${language}", which has no stemmer. Use one of ${list(STEMMER_LANGUAGES)}.`,
      );
    }
    result.set(key, language);
  }
  return result;
}

function localeFileName(locale: string): string {
  return locale.replace(/[^A-Za-z0-9_-]/g, "_") || DEFAULT_KEY;
}

function documentsFor(
  source: SourceSnapshot,
  locale: string | undefined,
): readonly TransformDocument[] {
  if (locale === undefined) return source.documents;
  return source.documents.filter(
    (document) =>
      document._meta.locale === undefined || document._meta.locale === locale,
  );
}

/** Name of a value's kind for errors (`Date`, `bigint`, `null`, …). */
function describe(value: StoreValue | RuntimeIndexValues | undefined): string {
  if (value === null) return "null";
  if (typeof value !== "object") return typeof value;
  const prototype: {
    readonly constructor?: { readonly name?: string };
  } | null = Object.getPrototypeOf(value);
  return prototype?.constructor?.name ?? "object";
}

/**
 * `store()` value as plain JSON. `undefined` object values are left out
 * (as `JSON.stringify` does); anything JSON cannot round-trip — `Date`,
 * `BigInt`, `NaN`, `Map`, class instances, functions — is an error.
 */
function storeJson(value: StoreValue, path: string): JsonValue {
  if (
    value === null ||
    typeof value === "string" ||
    typeof value === "boolean"
  ) {
    return value;
  }
  if (typeof value === "number") {
    if (Number.isFinite(value)) return value;
    throw new Error(`store() returned ${String(value)} at ${path}.`);
  }
  if (Array.isArray(value)) {
    return value.map((item: StoreValue | undefined, index) => {
      if (item === undefined) {
        throw new Error(`store() returned undefined at ${path}[${index}].`);
      }
      return storeJson(item, `${path}[${index}]`);
    });
  }
  if (isPlainObject(value)) {
    const result: { [key: string]: JsonValue } = {};
    for (const [key, item] of Object.entries(value)) {
      if (item !== undefined) {
        result[key] = storeJson(item, `${path}.${key}`);
      }
    }
    return result;
  }
  throw new Error(
    `store() returned a ${describe(value)} at ${path}; only JSON values are allowed (convert it, e.g. a Date with toISOString()).`,
  );
}

function storeFor(
  config: RuntimeCollection,
  document: TransformDocument,
): JsonObject {
  if (config.store === undefined) return {};
  const value = config.store(document);
  if (!isPlainObject(value)) {
    throw new Error(`store() must return an object, not ${describe(value)}.`);
  }
  const result: { [key: string]: JsonValue } = {};
  for (const [key, item] of Object.entries(value)) {
    if (item !== undefined) result[key] = storeJson(item, `store.${key}`);
  }
  return result;
}

function indexValues(
  name: string,
  config: RuntimeCollection,
  document: TransformDocument,
): RuntimeIndexValues {
  const values = config.index?.(document);
  if (!isPlainObject(values)) {
    throw new Error(`index() must return an object, not ${describe(values)}.`);
  }
  for (const key of Object.keys(values)) {
    if (!Object.hasOwn(config.schema, key)) {
      throw new Error(
        `index() returned "${key}", which is not in the "${name}" schema.`,
      );
    }
  }
  const fields = Object.keys(config.schema).flatMap((field) => {
    if (!Object.hasOwn(values, field)) {
      throw new Error(
        `index() did not return "${field}" (return undefined to leave it out).`,
      );
    }
    const value = values[field];
    return value === undefined ? [] : [[field, value] as const];
  });
  return Object.fromEntries(fields);
}

function rowFor(
  name: string,
  config: RuntimeCollection,
  document: TransformDocument,
) {
  return {
    ...indexValues(name, config, document),
    id: `${name}\u0000${document._meta.locale ?? ""}\u0000${document._meta.id}`,
    collection: name,
    documentId: document._meta.id,
    store: storeFor(config, document),
  };
}

/** JSON text as a single-quoted JS string literal (no `\"` for every quote). */
function jsonStringLiteral(json: string): string {
  const escaped = json
    .replaceAll("\\", "\\\\")
    .replaceAll("'", "\\'")
    .replaceAll(" ", "\\u2028")
    .replaceAll(" ", "\\u2029");
  return `'${escaped}'`;
}

/**
 * Build one Orama index per locale (monolingual documents are in every
 * locale), validate rows by inserting them, and emit:
 * - `<path>/<locale>.js` — the serialized index
 * - `<path>.js` — `loadSearchIndex(locale)` and `searchLocales`
 */
export async function generateSearchModules(
  options: RuntimeOramaOptions,
  context: PluginGenerateContext,
): Promise<void> {
  const base = options.path ?? "search";
  if (!/^[A-Za-z0-9_-]+$/.test(base)) {
    throw new Error(
      `orama: path "${base}" must be a simple name like "search".`,
    );
  }
  const byName = new Map(
    context.sources.map((source) => [source.name, source]),
  );
  for (const [name, config] of Object.entries(options.collections)) {
    const source = byName.get(name);
    if (!source || source.type !== "collection") {
      throw new Error(
        `orama: "${name}" is not a collection in defineConfig({ content }).`,
      );
    }
    if (config.index === undefined) {
      throw new Error(`orama: collection "${name}" needs an index() function.`);
    }
  }
  const schema = mergeSchemas(options.collections);
  const searchProperties = Object.entries(schema)
    .filter(([field, type]) => field !== "collection" && isSearchable(type))
    .map(([field]) => field);
  const collections = Object.keys(options.collections);
  const locales: readonly (string | undefined)[] =
    context.locales.length > 0 ? context.locales : [undefined];
  const keys = locales.map((locale) => locale ?? DEFAULT_KEY);
  const stemmers = stemmersByLocale(options.languages, keys);
  const loaders: string[] = [];

  for (const locale of locales) {
    const key = locale ?? DEFAULT_KEY;
    const stemmer = stemmers.get(key);
    const tokenizer: TokenizerSpec = {
      locale: locale ?? context.defaultLocale ?? "en",
      ...(stemmer === undefined ? {} : { stemmer }),
    };
    const db = create({
      schema,
      sort: { enabled: false },
      components: { tokenizer: await tokenizerFor(tokenizer) },
    });
    for (const [name, config] of Object.entries(options.collections)) {
      const source = byName.get(name);
      for (const document of source ? documentsFor(source, locale) : []) {
        try {
          insert(db, rowFor(name, config, document));
        } catch (cause) {
          throw new Error(
            `orama: ${name} document "${document._meta.id}" (${document._meta.filePath}): ${message(cause)}`,
            { cause },
          );
        }
      }
    }
    const snapshot: AnhurSearchIndex = {
      version: 4,
      locale: key,
      tokenizer,
      schema,
      searchProperties,
      collections,
      data: save(db),
    };
    const file = `${base}/${localeFileName(key)}.js`;
    context.emitModule({
      path: file,
      code: `${HEADER}\nexport default JSON.parse(${jsonStringLiteral(JSON.stringify(snapshot))});\n`,
    });
    loaders.push(
      `  [${JSON.stringify(key)}, () => import(${JSON.stringify(`./${file}`)})],`,
    );
  }

  const fallback = context.defaultLocale ?? DEFAULT_KEY;
  context.emitModule({
    path: `${base}.js`,
    exports: ["loadSearchIndex", "searchLocales"],
    code: [
      HEADER,
      `const loaders = new Map([\n${loaders.join("\n")}\n]);`,
      `export const searchLocales = ${JSON.stringify(keys)};`,
      "/** Load the search index of a locale (default locale when omitted); pass it to createSearcher(). */",
      "export async function loadSearchIndex(locale) {",
      `  const key = locale ?? ${JSON.stringify(fallback)};`,
      "  const loader = loaders.get(key);",
      '  if (!loader) throw new Error(`No search index for locale "${key}".`);',
      "  return (await loader()).default;",
      "}",
      "",
    ].join("\n"),
    dts: [
      'import type { AnhurSearchIndex as __AnhurOramaIndex, SearchStoresOf as __AnhurOramaStoresOf } from "@anhur/orama/client";',
      "/** Hit `store` type per collection (each collection's `store()` return type). */",
      `export type AnhurSearchStores = __AnhurOramaStoresOf<typeof __AnhurConfig, ${collections.map((name) => JSON.stringify(name)).join(" | ")}>;`,
      "/** String fields a search can match (`properties`, `boost`). */",
      `export type AnhurSearchField = ${searchProperties.map((field) => JSON.stringify(field)).join(" | ")};`,
      `export declare const searchLocales: readonly [${keys.map((key) => JSON.stringify(key)).join(", ")}];`,
      `export declare function loadSearchIndex(locale?: ${context.locales.length > 0 ? "Locale" : `"${DEFAULT_KEY}"`}): globalThis.Promise<__AnhurOramaIndex<AnhurSearchStores, AnhurSearchField>>;`,
    ].join("\n"),
  });
}
