import { plugins } from "bellona";
import { defineConfig } from "oxlint";

/**
 * Shared Oxlint baseline for Anhur packages and apps.
 *
 * Every rule of the bellona plugins this repo uses (js, react, base-ui, zod,
 * tanstack-router, effect, tailwind) is enabled explicitly. Bellona ships no
 * presets, so new bellona rules must be added here on upgrade.
 */
export default defineConfig({
  categories: {
    correctness: "error",
  },
  ignorePatterns: [
    "**/dist/**",
    "**/coverage/**",
    "**/build/**",
    "**/.output/**",
    "**/.nitro/**",
    "**/.turbo/**",
    "**/.anhur/**",
    "**/.temp/**",
    "**/.tmp/**",
    "**/.tanstack/**",
    "**/routeTree.gen.ts",
    "**/node_modules/**",
  ],
  jsPlugins: [
    plugins.js,
    plugins.react,
    plugins.baseUi,
    plugins.zod,
    plugins.tanstackRouter,
    plugins.effect,
    plugins.tailwind,
  ],
  rules: {
    // bellona/js
    "bl-js/no-chained-type-assertions": "error",
    "bl-js/no-generic-module-names": "error",
    "bl-js/no-inline-import-type": "error",
    "bl-js/no-known-value-widening": "error",
    "bl-js/no-module-mocking": "error",
    "bl-js/no-object-keys-assertion": "error",
    "bl-js/no-object-parameters": "error",
    "bl-js/no-runtime-typeof": ["error", { allowInTypeGuards: true }],
    "bl-js/no-shape-in-symbol-names": "error",
    "bl-js/no-unknown-parameters": [
      "error",
      { allow: ["cause", "value", "input"] },
    ],
    "bl-js/no-unknown-returns": "error",
    "bl-js/no-unknown-type-aliases": "error",
    "bl-js/no-unsafe-dictionary-type": "error",
    "bl-js/no-untyped-json": "error",
    "bl-js/no-useless-reexport": [
      "error",
      { allow: ["index.ts", "index.tsx", "oxfmt.config.ts"] },
    ],
    "bl-js/no-widen-then-assert": "error",
    "bl-js/require-file-layout": "error",
    "bl-js/require-own-key-lookup": "error",
    "bl-js/require-safety-comment-for-type-assertion": "error",

    // bellona/react
    "bl-react/component-file-name-match": [
      "error",
      { allow: ["/components/ui/"] },
    ],
    "bl-react/component-props-type": ["error", { allow: ["/components/ui/"] }],
    "bl-react/hook-file-name-match": "error",
    "bl-react/no-forward-ref": "error",
    "bl-react/no-impl-component-suffix": "error",
    "bl-react/no-jsx-iife-in-components": "error",
    "bl-react/no-jsx-local-constants-in-components": "error",
    "bl-react/no-jsx-module-constants": "error",
    "bl-react/no-jsx-variable-reassignment-in-components": "error",
    "bl-react/no-multi-component-files": [
      "error",
      { allow: ["/components/ui/"] },
    ],
    "bl-react/no-multi-hook-files": "error",
    "bl-react/no-native-html": "error",
    "bl-react/no-react-namespace": "error",
    "bl-react/no-render-helper-functions-in-components": "error",
    "bl-react/prefer-context-as-provider": "error",
    "bl-react/require-bare-hook-call": "error",

    // bellona/base-ui
    "bl-base-ui/no-component-as-render": "error",
    "bl-base-ui/require-native-button-with-render": "error",

    // bellona/zod
    "bl-zod/modern-format-validators": "error",
    "bl-zod/no-deprecated-v4-apis": "error",
    "bl-zod/schema-naming": "error",

    // bellona/tanstack-router
    "bl-tanstack-router/create-route-property-order": "error",
    "bl-tanstack-router/no-control-flow-outside-edge": "error",
    "bl-tanstack-router/no-deprecated-apis": "error",
    "bl-tanstack-router/no-dynamic-to": "error",
    "bl-tanstack-router/no-get-route-api": "error",
    "bl-tanstack-router/no-href": "error",
    "bl-tanstack-router/no-imperative-location-navigation": "error",
    "bl-tanstack-router/no-loader-data-in-not-found": "error",
    "bl-tanstack-router/no-not-found-in-component": "error",
    "bl-tanstack-router/no-not-found-route": "error",
    "bl-tanstack-router/no-relative-to-without-from": "error",
    "bl-tanstack-router/no-search-in-loader": "error",
    "bl-tanstack-router/no-type-assertion": "error",
    "bl-tanstack-router/no-whole-search-loader-deps": "error",
    "bl-tanstack-router/require-hook-from": "error",
    "bl-tanstack-router/require-inline-route-options": "error",
    "bl-tanstack-router/require-throw-not-found": "error",
    "bl-tanstack-router/require-throw-redirect": "error",

    // bellona/effect
    "bl-effect/effect-functions-in-services": "error",
    "bl-effect/max-service-methods": "error",
    "bl-effect/max-services": "error",
    "bl-effect/no-date-now": "error",
    "bl-effect/no-duplicate-layer-construction": "error",
    "bl-effect/no-eager-acquire": "error",
    "bl-effect/no-effect-run-in-tests": "error",
    "bl-effect/no-floating-effect": "error",
    "bl-effect/no-fork-detach": "error",
    "bl-effect/no-forwarding-service": "error",
    "bl-effect/no-inferred-service-contract": "error",
    "bl-effect/no-interpolated-log-message": "error",
    "bl-effect/no-it-scoped": "error",
    "bl-effect/no-log-and-rethrow": "error",
    "bl-effect/no-module-level-mutable-state": "error",
    "bl-effect/no-new-error-in-effect": "error",
    "bl-effect/no-per-call-cache-construction": "error",
    "bl-effect/no-return-effect-in-gen": "error",
    "bl-effect/no-run-promise-in-modules": [
      "error",
      { allow: ["/scripts/", "/cli/"] },
    ],
    "bl-effect/no-service-make-factory": "error",
    "bl-effect/no-silent-catch-cause": "error",
    "bl-effect/no-status-in-tagged-error": "error",
    "bl-effect/no-throw-in-gen": "error",
    "bl-effect/no-try-catch-in-gen": "error",
    "bl-effect/no-v3-apis": "error",
    "bl-effect/no-v3-imports": "error",
    "bl-effect/no-v3-service-tags": "error",
    "bl-effect/no-yield-ref-handle": "error",
    "bl-effect/prefer-clock-sleep": "error",
    "bl-effect/prefer-decode-unknown": "error",
    "bl-effect/prefer-fn": "error",
    "bl-effect/prefer-fn-untraced-in-callbacks": "error",
    "bl-effect/prefer-predicate": "error",
    "bl-effect/prefer-schema-tagged-error": "error",
    "bl-effect/prefer-service-of": "error",
    "bl-effect/prefer-try-promise": "error",
    "bl-effect/prefer-vitest": "error",
    "bl-effect/require-bounded-concurrency": "error",
    "bl-effect/require-bounded-retry": "error",
    "bl-effect/require-defect-cause": "error",
    "bl-effect/require-fn-name": "error",
    "bl-effect/require-fn-owner-prefix": "error",
    "bl-effect/require-fn-return-annotation": "error",
    "bl-effect/require-gen-self-options": "error",
    "bl-effect/require-ignore-log": "error",
    "bl-effect/require-promise-abort-signal": "error",
    "bl-effect/require-redacted-secret-config": "error",
    "bl-effect/require-return-yield-on-fail": "error",
    "bl-effect/require-service-filename": "error",
    "bl-effect/require-service-id-path": "error",
    "bl-effect/require-service-static-layer": "error",
    "bl-effect/require-timeout-on-external-io": "error",
    "bl-effect/schema-no-legacy-filter": "error",
    "bl-effect/schema-union-array": "error",

    // bellona/tailwind
    "bl-tailwind/no-classname-constants": "error",
    "bl-tailwind/no-dynamic-class-construction": "error",
    "bl-tailwind/no-v3-arbitrary-var": "error",
  },
});
