import { plugins } from "bellona";
import { defineConfig } from "oxlint";

/** Shared Oxlint baseline for Anhur packages and apps. */
export default defineConfig({
  categories: {
    correctness: "error",
  },
  ignorePatterns: [
    "**/dist/**",
    "**/coverage/**",
    "**/build/**",
    "**/.output/**",
    "**/.nitro/**",
    "**/.turbo/**",
    "**/.anhur/**",
    "**/.temp/**",
    "**/.tanstack/**",
    "**/routeTree.gen.ts",
    "**/node_modules/**",
  ],
  jsPlugins: [
    plugins.js,
    plugins.react,
    plugins.baseUi,
    plugins.zod,
    plugins.tanstackRouter,
    plugins.effect,
    plugins.tailwind,
  ],
  rules: {
    "bl-js/max-classes": "error",
    "bl-js/no-chained-type-assertions": "error",
    "bl-js/no-conditional-empty-object-spread": "error",
    "bl-js/no-inline-import-type": "error",
    "bl-js/no-known-value-widening": "error",
    "bl-js/no-module-mocking": "error",
    "bl-js/no-object-parameters": "error",
    "bl-js/no-reflect-apply": "error",
    "bl-js/no-reflect-get": "error",
    "bl-js/no-runtime-typeof": ["error", { allowInTypeGuards: true }],
    "bl-js/no-shape-in-symbol-names": "error",
    "bl-js/no-unknown-parameters": ["error", { allow: ["cause", "value", "input"] }],
    "bl-js/no-unknown-returns": "error",
    "bl-js/no-unknown-type-aliases": "error",
    "bl-js/no-unsafe-dictionary-type": "error",
    "bl-js/no-useless-reexport": [
      "error",
      { allow: ["src/index.ts", "src/index.tsx", "oxfmt.config.ts"] },
    ],
    "bl-js/no-widen-then-assert": "error",
    "bl-js/require-safety-comment-for-type-assertion": "error",
    "bl-react/component-file-name-match": ["error", { allow: ["/components/ui/"] }],
    "bl-react/component-props-type": ["error", { allow: ["/components/ui/"] }],
    "bl-react/hook-file-name-match": "error",
    "bl-react/no-impl-component-suffix": "error",
    "bl-react/no-jsx-iife-in-components": "error",
    "bl-react/no-jsx-local-constants-in-components": "error",
    "bl-react/no-jsx-module-constants": "error",
    "bl-react/no-jsx-variable-reassignment-in-components": "error",
    "bl-react/no-multi-component-files": ["error", { allow: ["/components/ui/"] }],
    "bl-react/no-multi-hook-files": "error",
    "bl-react/no-native-html": "error",
    "bl-react/no-namespace": ["error", { allow: ["/components/ui/"] }],
    "bl-react/no-render-helper-functions-in-components": "error",
    "bl-react/require-bare-hook-call": "error",
    "bl-base-ui/require-native-button-with-render": "error",
    "bl-zod/modern-format-validators": "error",
    "bl-zod/schema-naming": "error",
    "bl-tanstack-router/create-route-property-order": "error",
    "bl-tanstack-router/no-control-flow-outside-edge": "error",
    "bl-tanstack-router/no-dynamic-to": "error",
    "bl-tanstack-router/no-get-route-api": "error",
    "bl-tanstack-router/no-hooks-in-route-lifecycle": "error",
    "bl-tanstack-router/no-imperative-location-navigation": "error",
    "bl-tanstack-router/no-loader-data-in-not-found": "error",
    "bl-tanstack-router/no-not-found-in-component": "error",
    "bl-tanstack-router/no-not-found-route": "error",
    "bl-tanstack-router/no-relative-to-without-from": "error",
    "bl-tanstack-router/no-href": "error",
    "bl-tanstack-router/no-type-assertion": "error",
    "bl-tanstack-router/no-search-in-loader": "error",
    "bl-tanstack-router/require-params-with-path-tokens": "error",
    "bl-tanstack-router/require-hook-from": "error",
    "bl-tanstack-router/require-inline-route-options": "error",
    "bl-tanstack-router/require-throw-not-found": "error",
    "bl-tanstack-router/require-throw-redirect": "error",
    "bl-tanstack-router/require-validate-search-when-used": "error",
    "bl-effect/no-v3-apis": "error",
    "bl-effect/no-v3-imports": "error",
    "bl-effect/no-v3-service-tags": "error",
    "bl-effect/prefer-fn": "error",
    "bl-effect/require-fn-name": "error",
    "bl-effect/no-pipe-on-fn": "error",
    "bl-effect/no-try-catch-in-gen": "error",
    "bl-effect/no-throw-in-gen": "error",
    "bl-effect/require-gen-self-options": "error",
    "bl-effect/require-return-yield-on-fail": "error",
    "bl-effect/schema-union-array": "error",
    "bl-effect/prefer-date-from-string": "error",
    "bl-effect/prefer-decode-unknown": "error",
    "bl-effect/no-it-scoped": "error",
    "bl-effect/no-run-promise-in-modules": ["error", { allow: ["/scripts/", "/cli/"] }],
    "bl-effect/require-service-id-path": "error",
    "bl-effect/require-service-static-layer": "error",
    "bl-effect/prefer-service-of": "error",
    "bl-effect/no-date-now": "error",
    "bl-effect/prefer-clock-sleep": "error",
    "bl-effect/prefer-schema-tagged-error": "error",
    "bl-effect/prefer-try-promise": "error",
    "bl-effect/prefer-predicate": "error",
    "bl-effect/no-yield-ref-handle": "error",
    "bl-effect/prefer-vitest": "error",
    "bl-effect/schema-no-legacy-filter": "error",
    "bl-tailwind/no-classname-constants": "error",
  },
});
